# Generated by Django 4.0.4 on 2022-12-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_Pharmacist',
            field=models.BooleanField(default=False, verbose_name='Pharmacist status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_Technician',
            field=models.BooleanField(default=False, verbose_name='Technician status'),
        ),
    ]
