# Generated by Django 4.0.4 on 2022-12-07 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('patient_first_name', models.CharField(max_length=255)),
                ('patient_middle_name', models.CharField(max_length=255)),
                ('patient_last_name', models.CharField(max_length=255)),
                ('patient_dob', models.DateField(max_length=8)),
                ('generic_name', models.CharField(max_length=255)),
                ('ndc', models.IntegerField()),
                ('dosage', models.CharField(max_length=255)),
                ('vessel', models.CharField(max_length=255)),
                ('volume', models.CharField(max_length=255)),
                ('lot_number', models.CharField(max_length=255)),
                ('expiration', models.DateField(max_length=8)),
                ('sig', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
                ('ordering_doctor', models.CharField(max_length=255)),
                ('ordering_doctor_phone_number', models.CharField(max_length=255)),
                ('indication', models.CharField(max_length=255)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_profile.patient')),
            ],
        ),
    ]
