# Generated by Django 4.0.4 on 2022-12-07 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_profile', '0001_initial'),
        ('prescription', '0006_alter_prescription_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_profile.patient'),
        ),
    ]
