# Generated by Django 4.0.4 on 2022-12-07 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0009_alter_prescription_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
