# Generated by Django 4.0.4 on 2022-12-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0012_alter_prescription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='expiration',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='lot_number',
        ),
    ]
