# Generated by Django 4.0.4 on 2022-12-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0013_remove_prescription_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='verified',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
