# Generated by Django 4.0.4 on 2022-12-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='phone_number',
        ),
    ]
