# Generated by Django 4.0.4 on 2022-12-07 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medication', '0001_initial'),
        ('patient_profile', '0001_initial'),
        ('prescription', '0005_alter_prescription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_last_name', models.CharField(max_length=255)),
                ('patient_dob', models.CharField(max_length=255)),
                ('prescription_generic_name', models.CharField(max_length=255)),
                ('prescription_dosage', models.CharField(max_length=255)),
                ('medication_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.medication')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_profile.patient')),
                ('prescription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.prescription')),
            ],
        ),
    ]
