# Generated by Django 4.0.4 on 2022-12-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='patient_dob',
            field=models.DateField(max_length=8),
        ),
    ]
