# Generated by Django 4.0.4 on 2022-12-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_production_patient_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='medication_id',
            new_name='medication',
        ),
        migrations.RenameField(
            model_name='production',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='production',
            old_name='prescription_id',
            new_name='prescription',
        ),
    ]
