# Generated by Django 4.0.4 on 2022-12-13 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_rename_medication_id_production_medication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='production',
            name='patient_dob',
        ),
        migrations.RemoveField(
            model_name='production',
            name='patient_last_name',
        ),
        migrations.AddField(
            model_name='production',
            name='expiration',
            field=models.DateField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='production',
            name='lot_number',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='production',
            name='ndc',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
