# Generated by Django 4.0.4 on 2022-12-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_remove_production_medication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='verified',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
